package com.example.movieworld.movieDetails

data class Movie(
    val id: String,
    val actors: String,
    val directorName: String,
    val writerName: String,
    val releaseDate: String,
    val movieRating: Double,
    val moviePosterUrl: String,
    val otherPoster: List<String>,
    val story: String
)

fun getMovies(): List<Movie> {
    return listOf(
        Movie(
            id = "Pathaan",
            actors = "Shah Rukh Khan, Deepika Padukone, John Abraham",
            directorName = "Siddharth Anand",
            writerName = "Shridhar Raghavan",
            releaseDate = "January 25, 2023",
            movieRating = 8.5,
            moviePosterUrl = "https://stat4.bollywoodhungama.in/wp-content/uploads/2020/08/Pathaan-01.jpg",
            otherPoster = listOf("https://stat4.bollywoodhungama.in/wp-content/uploads/2020/08/Pathaan-12.jpg",
                "https://media5.bollywoodhungama.in/wp-content/uploads/2020/08/Pathaan-10.jpg",
                "https://media5.bollywoodhungama.in/wp-content/uploads/2020/08/Pathaan-9.jpg",
                "https://stat5.bollywoodhungama.in/wp-content/uploads/2020/08/Pathaan-6.jpg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2020/08/Pathaan-8.jpg"),
            story = "Pathaan, a fearless RAW agent, who goes on a mission to neutralize a terrorist group planning a series of attacks in India. He is joined by Rubina, an ISI agent, and Jim, a former mercenary, in his quest to save the country."
        ),
        Movie(
            id = "Bhediya",
            actors = "Varun Dhawan, Kriti Sanon, Abhishek Banerjee",
            directorName = "Amar Kaushik",
            writerName = "Niren Bhatt",
            releaseDate = "November 25, 2022",
            movieRating = 7.8,
            moviePosterUrl = "https://media5.bollywoodhungama.in/wp-content/uploads/2020/10/Bhediya-7.jpg",
            otherPoster = listOf("https://media5.bollywoodhungama.in/wp-content/uploads/2020/10/Bhediya-8.jpg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2020/10/Bhediya-6.jpg",
                "https://media5.bollywoodhungama.in/wp-content/uploads/2020/10/Bhediya-3.jpg",
                "https://media5.bollywoodhungama.in/wp-content/uploads/2020/10/Bhediya-1.jpg",
                "https://stat5.bollywoodhungama.in/wp-content/uploads/2022/11/Bhediya-1.jpg"),
            story = "A man gets bitten by a mythical werewolf and transforms into a creature with extraordinary powers. He must learn to control his new abilities while also discovering the truth behind his transformation."
        ),
        Movie(
            id = "Drishyam2",
            actors = "Ajay Devgn, Tabu, Akshaye Khanna",
            directorName = "Abhishek Pathak",
            writerName = "Aamil Keeyan Khan",
            releaseDate = "November 18, 2022",
            movieRating = 8.2,
            moviePosterUrl = "https://stat5.bollywoodhungama.in/wp-content/uploads/2021/02/Drishyam-2-3.jpg",
            otherPoster = listOf("https://stat5.bollywoodhungama.in/wp-content/uploads/2021/02/Drishyam-2-9.jpg",
                "https://media5.bollywoodhungama.in/wp-content/uploads/2021/02/Drishyam-2-7.jpg",
                "https://media5.bollywoodhungama.in/wp-content/uploads/2022/11/Drishyam-2-12-2.jpg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2022/11/Drishyam-2-2-3.jpg",
                "https://stat5.bollywoodhungama.in/wp-content/uploads/2022/11/Drishyam-2-4-1.jpg"),
            story = "Seven years after the events of the first film, Vijay Salgaonkar's family is still reeling from the trauma of the past. When an old enemy returns to seek revenge, Vijay must once again protect his family and uncover the truth behind a long-buried secret."
        ),
        Movie(
            id = "AnActionHero",
            actors = "Ayushmann Khurrana, Jaideep Ahlawat",
            directorName = "Anirudh Iyer",
            writerName = "Neeraj Yadav",
            releaseDate = "December 2, 2022",
            movieRating = 7.5,
            moviePosterUrl = "https://media5.bollywoodhungama.in/wp-content/uploads/2022/11/An-Action-Hero-12.jpg",
            otherPoster = listOf("https://media5.bollywoodhungama.in/wp-content/uploads/2023/02/An-Action-Hero-1.jpg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2023/02/An-Action-Hero-2.jpg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2022/01/An-Action-Hero-00-1.jpg"),
            story = "Maanav Khurana, a celebrated action hero, finds himself caught in a dangerous trap when he accidentally kills a man. He must now outrun a corrupt politician and his henchmen, who are determined to silence him."
        ),
        Movie(
            id = "Mili",
            actors = "Janhvi Kapoor, Sunny Kaushal, Manoj Pahwa",
            directorName = "Mathukutty Xavier",
            writerName = "Ritesh Shah",
            releaseDate = "November 4, 2022",
            movieRating = 7.2,
            moviePosterUrl = "https://media5.bollywoodhungama.in/wp-content/uploads/2022/10/Mili-4.jpg",
            otherPoster = listOf("https://stat4.bollywoodhungama.in/wp-content/uploads/2022/11/Mili.jpg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2022/10/Mili.jpeg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2022/10/Mili-2-1.jpg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2022/11/Mili-2.jpg"),
            story = "Mili Naudiyal, a young nursing graduate, gets trapped in a freezer while working at a local supermarket. She must find a way to survive and escape before it's too late."
        ),
        Movie(
            id = "PhoneBhoot",
            actors = "Katrina Kaif, Ishaan Khatter, Siddhant Chaturvedi",
            directorName = "Gurmmeet Singh",
            writerName = "Ravi Shankaran, Jasvinder Singh Bath",
            releaseDate = "November 4, 2022",
            movieRating = 6.5,
            moviePosterUrl = "https://stat4.bollywoodhungama.in/wp-content/uploads/2022/10/PhoneBhoot.jpeg",
            otherPoster = listOf("https://stat4.bollywoodhungama.in/wp-content/uploads/2022/07/PhoneBhoot.jpeg",
                "https://media5.bollywoodhungama.in/wp-content/uploads/2022/06/PhoneBhoot.jpg",),
            story = "In the Mumbai suburbs, three friends: Gale, Major and Raghav get their lives turned upside down when they come across a spirit called Ragini who is haunting their gym. Their lives take a weirder turn when they meet a ghostbuster called Maya who offers them a job at her agency - PhoneBhoot. The trio embrace their new mission and set out to make the world a ghost-free place while also dealing with their own personal demons."
        ),
        Movie(
            id = "DoubleXL",
            actors = "Sonakshi Sinha, Huma Qureshi, Zaheer Iqbal",
            directorName = "Satramm Ramani",
            writerName = "Mudassar Aziz",
            releaseDate = "November 4, 2022",
            movieRating = 6.0,
            moviePosterUrl = "https://stat4.bollywoodhungama.in/wp-content/uploads/2022/10/Double-XL.jpeg",
            otherPoster = listOf("https://stat5.bollywoodhungama.in/wp-content/uploads/2022/10/Double-XL-3.jpg",
                "https://stat5.bollywoodhungama.in/wp-content/uploads/2022/10/Double-XL-2.jpg"),
            story = "The film follows two plus-size women, Rajshree Trivedi and Saira Khanna, as they navigate the world of fashion and body image stereotypes. Rajshree, a fashion designer, and Saira, a sports presenter, team up to launch a clothing line that celebrates curvy bodies. As they face challenges and societal pressures, they learn to embrace themselves and their beauty, inspiring others to do the same."
        ),
        Movie(
            id = "ThankGod",
            actors = "Ajay Devgn, Sidharth Malhotra, Rakul Preet Singh",
            directorName = "Indra Kumar",
            writerName = "Aakash Kaushik",
            releaseDate = "October 25, 2022",
            movieRating = 5.5,
            moviePosterUrl = "https://media5.bollywoodhungama.in/wp-content/uploads/2022/09/Thank-God.jpg",
            otherPoster = listOf("https://stat5.bollywoodhungama.in/wp-content/uploads/2021/08/Thank-God.jpg",
                "https://media5.bollywoodhungama.in/wp-content/uploads/2022/09/Thank-God-2.jpg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2022/09/Thank-God-1-1.jpg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2022/09/Thank-God-1.jpeg"),
            story = "Aayush Kapoor, a businessman, finds himself in a strange place called \"Yamlok\" after a near-death experience. He meets Chitragupt, the accountant of the afterlife, who shows him various scenarios from his life and explains the concept of karma. Aayush is given a chance to return to Earth and make amends for his mistakes, with the help of a mysterious figure named Sidharth."
        ),
        Movie(
            id = "RamSetu",
            actors = "Akshay Kumar, Jacqueline Fernandez, Nushrratt Bharuccha",
            directorName = "Abhishek Sharma",
            writerName = "Chandraprakash Dwivedi",
            releaseDate = "October 25, 2022",
            movieRating = 7.5,
            moviePosterUrl = "https://media5.bollywoodhungama.in/wp-content/uploads/2022/12/Ram-Setu.jpg",
            otherPoster = listOf("https://stat5.bollywoodhungama.in/wp-content/uploads/2022/10/Ram-Setu-6.jpg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2022/10/Ram-Setu-4.jpeg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2022/10/Ram-Setu-3.jpeg",
                "https://media5.bollywoodhungama.in/wp-content/uploads/2022/10/Ram-Setu-1.jpg",
                "https://stat5.bollywoodhungama.in/wp-content/uploads/2022/10/Ram-Setu-2.jpeg",
                "https://stat5.bollywoodhungama.in/wp-content/uploads/2022/04/Ram-Setu.jpg"),
            story = "Archeologist Dr. Aryan Kulshrestha is on a mission to prove the existence of Ram Setu, a legendary bridge between India and Sri Lanka. He believes that the bridge was built by Lord Rama and that it holds immense historical and religious significance. However, he faces opposition from a powerful businessman, Indrakant Vajpayee, who plans to destroy the bridge for personal gain. Aryan teams up with marine biologist Dr. Sandra Rathore and a local fisherman named Kapil to uncover the truth about Ram Setu and protect it from destruction."
        ),
        Movie(
            id = "Adipurush",
            actors = "Prabhas, Kriti Sanon, Saif Ali Khan",
            directorName = "Om Raut",
            writerName = "Raghuram Rajan",
            releaseDate = "January 12, 2023",
            movieRating = 3.8,
            moviePosterUrl = "https://stat5.bollywoodhungama.in/wp-content/uploads/2023/05/Adipurush.jpg",
            otherPoster = listOf("https://media5.bollywoodhungama.in/wp-content/uploads/2023/04/Adipurush-6.jpg",
                "https://stat5.bollywoodhungama.in/wp-content/uploads/2023/04/Adipurush-5.jpg",
                "https://stat5.bollywoodhungama.in/wp-content/uploads/2023/06/Adipurush-1-3.jpg",
                "https://media5.bollywoodhungama.in/wp-content/uploads/2020/08/Adipurush-3.jpg",
                "https://stat5.bollywoodhungama.in/wp-content/uploads/2020/08/Adipurush-4.jpg"),
            story = "The film is an adaptation of the Hindu epic Ramayana. It tells the story of Lord Rama, a prince who is exiled to the forest with his wife Sita and brother Lakshmana. During their exile, they encounter various challenges and obstacles, including the demon king Ravana. Rama and Ravana engage in a fierce battle, and ultimately, Rama emerges victorious and rescues Sita."
        ),
        Movie(
            id = "Ganapath",
            actors = "Tiger Shroff, Kriti Sanon, Amitabh Bachchan",
            directorName = "Vikas Bahl",
            writerName = "Parveez Sheikh",
            releaseDate = "October 20, 2023",
            movieRating = 5.1,
            moviePosterUrl = "https://stat5.bollywoodhungama.in/wp-content/uploads/2023/10/Ganapath-A-Hero-Is-Born.jpeg",
            otherPoster = listOf("https://stat5.bollywoodhungama.in/wp-content/uploads/2023/09/Ganapath-A-Hero-Is-Born.jpg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2020/10/Ganapath-–-A-Hero-Is-Born-8.jpg",
                "https://media5.bollywoodhungama.in/wp-content/uploads/2020/10/Ganapath-–-A-Hero-Is-Born-7.jpg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2020/10/Ganapath-–-A-Hero-Is-Born-3.jpg",
                "https://stat5.bollywoodhungama.in/wp-content/uploads/2020/10/Ganapath-–-A-Hero-Is-Born-6.jpg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2020/10/Ganapath-–-A-Hero-Is-Born-4.jpg",
                "https://stat5.bollywoodhungama.in/wp-content/uploads/2020/10/Ganapath-Part-1.jpg",
                "https://media5.bollywoodhungama.in/wp-content/uploads/2020/10/Ganapath-–-A-Hero-Is-Born-5.jpg"),
            story = "In a post-apocalyptic world ravaged by a virus, a young man named Ganapath is forced to become a fighter to survive. He sets out on a journey to find his lost love, Rasika, and along the way, he encounters various dangers and enemies. Ganapath must use his skills and determination to overcome these challenges and find Rasika, while also fighting for a better future for humanity."
        ),
        Movie(
            id = "Satyaprem Ki Katha",
            actors = "Kartik Aaryan, Kiara Advani",
            directorName = "Sameer Vidwans",
            writerName = "Sameer Vidwans",
            releaseDate = "June 29, 2023",
            movieRating = 7.2, // Add the actual rating
            moviePosterUrl = "https://media5.bollywoodhungama.in/wp-content/uploads/2023/05/Satyaprem-Ki-Katha-1.jpg",
            otherPoster = listOf("https://stat5.bollywoodhungama.in/wp-content/uploads/2023/06/Satyaprem-Ki-Katha-1.jpg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2023/06/Satyaprem-Ki-Katha.jpg",
                "https://stat5.bollywoodhungama.in/wp-content/uploads/2023/06/Satyaprem-Ki-Katha-7.jpg"),
            story = "Satyaprem Ki Katha is a romantic drama that follows the journey of Satya and Prem, two individuals from different backgrounds who fall in love. Satya is a middle-class girl from a small town, while Prem is a wealthy businessman from Mumbai. As they navigate the challenges and obstacles that come their way, they learn the true meaning of love and commitment."
        ),
        Movie(
            id = "Dunki",
            actors = "Shah Rukh Khan, Taapsee Pannu",
            directorName = "Rajkumar Hirani",
            writerName = "Rajkumar Hirani, Abhijat Joshi",
            releaseDate = "December 22, 2023",
            movieRating = 7.6, // Add the actual rating
            moviePosterUrl = "https://media5.bollywoodhungama.in/wp-content/uploads/2023/11/Dunki-2.jpeg",
            otherPoster = listOf("https://stat5.bollywoodhungama.in/wp-content/uploads/2023/12/Dunki.jpeg",
                "https://stat4.bollywoodhungama.in/wp-content/uploads/2023/12/Dunki-1-13.jpg",
                "https://media5.bollywoodhungama.in/wp-content/uploads/2023/12/Dunki-2.jpg",
                "https://stat5.bollywoodhungama.in/wp-content/uploads/2023/11/Dunki-2-4.jpg",
                "https://stat5.bollywoodhungama.in/wp-content/uploads/2023/11/Dunki-2-1.jpg"),
            story = "Dunki is a comedy-drama that revolves around the life of Dunki (Shah Rukh Khan), a free-spirited Punjabi man living in Canada. Dunki finds himself on an extraordinary journey when he meets a fiery and independent woman named Su (Taapsee Pannu), who challenges his beliefs and perspectives on life. As they navigate cultural differences, societal norms, and their own personal baggage, Dunki discovers the true meaning of love and friendship while embarking on an adventure that will change his life forever."
        )
    )
}
